# Generated by Django 4.2.7 on 2024-02-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TouchGrassApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='latitude',
            field=models.DecimalField(decimal_places=20, default=1, max_digits=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facility',
            name='longitude',
            field=models.DecimalField(decimal_places=20, default=1, max_digits=25),
            preserve_default=False,
        ),
    ]
