# Generated by Django 4.2.7 on 2024-02-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TouchGrassApp', '0002_facility_latitude_facility_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('facilities', models.ManyToManyField(related_name='activities', to='TouchGrassApp.facility')),
            ],
        ),
    ]
